[project]
name = "10-rl-hf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gymnasium>=1.2.0",
    "loguru>=0.7.3",
    "matplotlib>=3.10.5",
    "pygame>=2.6.1",
    "tqdm>=4.67.1",
]
